# This is example input yaml for count_data_validations() and row_data_validations() functions.
# This file is not being used in the code anywhere, but we have added to provide the example here. 
# User needs to provide this yaml as input in the count_data_validations() and row_data_validations() function.
# Replace the tables names with your's to proceed for the count validation using count_data_validations()
# and row data validation using row_data_validations()
rows:
  - is_validation_active: True
    table1: 'hive_metastore.mart_mops.mops_ad_hierarchy'
    table2: 'sandbox_marketing.mart_mops_test.mops_ad_hierarchy'
    filter_condition: ""
    materialization: 'incremental'

  - is_validation_active: True
    table1: 'hive_metastore.mart_mops.mops_b2cplanningmetrics'
    table2: 'sandbox_marketing.mart_mops_test.mops_b2cplanningmetrics'
    filter_condition: ""
    materialization: 'incremental'

  - is_validation_active: True
    table1: 'hive_metastore.mart_mops.agent_ltv'
    table2: 'sandbox_marketing.mart_mops_test.agent_ltv'
    filter_condition: ""
    materialization: 'incremental'  

  - is_validation_active: False
    table1: 'hive_metastore.mart_mops.mops_omp_fact'
    table2: 'sandbox_marketing.mart_mops_test.mops_omp_fact'
    filter_condition: "data_date >= date'2024-04-01'"
    materialization: 'incremental'

  - is_validation_active: True
    table1: 'hive_metastore.mart_mops.agentacademy'
    table2: 'sandbox_marketing.mart_mops_test.agentacademy'
    filter_condition: ""
    materialization: 'incremental'

  - is_validation_active: True
    table1: 'hive_metastore.mart_mops.mops_b2c_measurments_fact'
    table2: 'sandbox_marketing.mart_mops_test.mops_b2c_measurments_fact'
    filter_condition: "process_year = 2024"
    materialization: 'incremental'

  - is_validation_active: True
    table1: 'hive_metastore.mart_mops.real_time_touring_agent'
    table2: 'sandbox_marketing.mart_mops_test.real_time_touring_agent_managed'
    filter_condition: "p_data_date >= date'2024-05-16'"
    materialization: 'incremental'
    metric_validation_active: True
    ignored_columns: 'mls_id, team_lead'
    dimenssion_columns: 'p_data_date'
    dim_metrics_columns: 'team_lead, mls_id'
